# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            cybette
tagline:          Carol Chen
description:      Open Source Community Developer | Red Hatter | Professional Geek | Amateur Musician
url:              https://cybette.github.io
baseurl:          /

author:
  name:           'Carol Chen'
  url:            https://twitter.com/cybette

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/cybette/cybette.github.io

profilepic:       cybette.png

# Profile links on the left sidebar
social:
  github:         cybette
  hacker_news:    cybette
  twitter:        cybette
  facebook:       cybette
  linkedin:       cybette
  gplus:          110018497137161565750

# Toggle link/icon to view atom feed (/atom.xml) in sidebar
show_atom_feed:   true

# Google Analytics key, leave blank to ignore
google_analytics_key: UA-100083417-1

