# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            cybette
tagline:          Carol Chen
description:      Open Source Community Developer | Red Hatter | Professional Geek | Amateur Musician
url:              https://cybette.github.io
baseurl:          /

author:
  name:           'Carol Chen'
  url:            https://twitter.com/cybette

paginate:         5

# Custom vars
# version:          1.0.1

github:
  repo:           https://github.com/cybette/cybette.github.io
